name: default
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8
    - numpy=1.21.2
    - pandas=1.3.2
    - scipy=1.6.2
    - statsmodels=0.13.0
    - tqdm=4.48.0
    - requests
    - multiprocess
    - sqlalchemy

